# Generated by Django 5.1.1 on 2024-09-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_event_remove_contact_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
