# Generated by Django 5.1.1 on 2024-09-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_porta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='porta',
            name='image',
            field=models.ImageField(default='path/to/default_image.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='porta',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
