# Generated by Django 5.1.1 on 2024-10-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_porta_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonio',
            name='empresa',
            field=models.CharField(default='Empresa Desconocida', max_length=100),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='puesto',
            field=models.CharField(default='Puesto Desconocido', max_length=100),
        ),
    ]
